# Generated by Django 4.2.7 on 2025-11-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_records', models.IntegerField(default=0)),
                ('summary_stats', models.JSONField(blank=True, default=dict)),
                ('equipment_types', models.JSONField(blank=True, default=dict)),
                ('file_size', models.IntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_type', models.CharField(default='summary', max_length=50)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['-uploaded_at'], name='analyzer_da_uploade_cd9b37_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['user', '-uploaded_at'], name='analyzer_da_user_id_0ee585_idx'),
        ),
    ]
